<h3>
    <i class="fas fa-user"></i> Création d'un compte client
</h3>

<form action="<?= $requestUrl ?>/user/create" method="post" class="generic-form">
    <fieldset>
        <legend><i class="fas fa-book"></i> Identité et coordonnées</legend>
        <ul>
            <li>
                <label for="last_name">Nom :</label>
                <input type="text" name="last_name" id="last_name">
            </li>
            <li>
                <label for="first_name">Prénom :</label>
                <input type="text" name="first_name" id="first_name">
            </li>
            <li>
                <label for="address">Adresse :</label>
                <textarea name="address" id="address" rows="3"></textarea>
            </li>
            <li>
                <label for="zip_code">Code Postal :</label>
                <input type="text" name="zip_code" id="zip_code">
            </li>
            <li>
                <label for="city">Ville :</label>
                <input type="text" name="city" id="city">
            </li>
            <li>
                <label for="phone">Téléphone :</label>
                <input type="text" name="phone" id="phone">
            </li>
        </ul>
    </fieldset>
    <fieldset>
        <legend><i class="fas fa-lock"></i> Informations de connexion</legend>
        <ul>
            <li>
                <label for="email">Email :</label>
                <input type="text" name="email" id="email">
            </li>
            <li>
                <label for="password">Mot de passe :</label>
                <input type="password" name="password" id="password">
                <input type="password" name="password-verification"
                       id="password-verification" placeholder="Confirmation de mot de passe">
            </li>
        </ul>
    </fieldset>
    <ul>
        <li>
            <input type="submit" class="button button-primary" value="Créer le compte">
            <a href="<?= $requestUrl ?>" class="button button-cancel small">Annuler</a>
        </li>
    </ul>
</form>