<h3>
    <i class="fas fa-user"></i> Création d'un compte client
</h3>

<form action="<?= $requestUrl ?>/user/create" method="post" class="generic-form">
    <aside class="error-message hidden">
        <h3>
            <i class="fas fa-exclamation-triangle"></i>
            Il y a <span class="total-error-count">1</span> erreur(s) dans le formulaire !
        </h3>
        <p><?= $errorMessage ?></p>
    </aside>
    <fieldset>
        <legend><i class="fas fa-book"></i> Identité et coordonnées</legend>
        <ul>
            <li>
                <label for="last_name">Nom* :</label>
                <input type="text" name="last_name" id="last_name" value="<?= $last_name ?>" 
                       data-name="Nom" data-required data-minlength="2">
            </li>
            <li>
                <label for="first_name">Prénom* :</label>
                <input type="text" name="first_name" id="first_name" value="<?= $first_name ?>" 
                       data-name="Prénom" data-required data-minlength="2">
            </li>
            <li>
                <label for="address">Adresse :</label>
                <textarea name="address" id="address" rows="3" 
                          data-name="Adresse" data-minlength="3"><?= $address ?></textarea>
            </li>
            <li>
                <label for="zip_code">Code Postal :</label>
                <input type="text" name="zip_code" id="zip_code" value="<?= $zip_code ?>" 
                       data-name="Code Postal" data-minlength="4" data-type="number">
            </li>
            <li>
                <label for="city">Ville :</label>
                <input type="text" name="city" id="city" value="<?= $city ?>" 
                    data-name="Ville" data-minlength="2">
            </li>
            <li>
                <label for="phone">Téléphone :</label>
                <input type="text" name="phone" id="phone" value="<?= $phone ?>" 
                       data-name="Téléphone" data-minlength="10" data-type="number">
            </li>
        </ul>
    </fieldset>
    <fieldset>
        <legend><i class="fas fa-lock"></i> Informations de connexion</legend>
        <ul>
            <li>
                <label for="email">Email* :</label>
                <input type="email" name="email" id="email" value="<?= $email ?>" 
                       data-name="E-mail" data-required>
            </li>
            <li>
                <label for="password">Mot de passe* :</label>
                <input type="password" name="password" id="password" 
                       data-name="Mot de passe" data-required>
                <input type="password" name="password-verification"
                       id="password-verification" placeholder="Confirmation de mot de passe" 
                       data-name="Confirmation de mot de passe">
            </li>
        </ul>
    </fieldset>
    <ul>
        <li>
            <input type="submit" class="button button-primary" value="Créer le compte">
            <a href="<?= $requestUrl ?>" class="button button-cancel small">Annuler</a>
        </li>
    </ul>
</form>