<h3>
    <i class="fas fa-lock"></i> Connexion
</h3>

<form method="post" class="generic-form">
    <aside class="error-message hidden">
        <h3>
            <i class="fas fa-exclamation-triangle"></i> Il y a <span class="total-error-count">1</span>
            erreur(s) dans le formulaire !
        </h3>
        <p><?= $errorMessage ?></p>
    </aside>
    <fieldset>
        <legend><i class="fas fa-lock"></i> Informations de connexion</legend>
        <ul>
            <li>
                <label for="email">Email :</label>
                <input type="text" name="email" id="email" value="<?= $email ?>"
                       data-name="Email" data-required>
            </li>
            <li>
                <label for="password">Mot de passe :</label>
                <input type="password" name="password" id="password"
                       data-name="Mot de passe" data-required>
            </li>
        </ul>
    </fieldset>
    <ul>
        <li>
            <input type="submit" class="button button-primary" value="Connexion">
            <a href="<?= $requestUrl ?>" class="button button-cancel small">Annuler</a>
        </li>
    </ul>
</form>