<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title><?= $pageTitle ?? '3WA Restaurant' ?></title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome/css/all.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In
            America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <li>
            <a href="<?= $requestUrl ?>/user/create" class="button button-primary">Créer un compte</a>
        </li>
            <?php 
                $userSession = new UserSession();
                if($userSession->isAuthentificated()): 
            ?>
        <li>
            <a href="<?= $requestUrl ?>/login" class="button button-primary">Commander</a>
        </li>
        <li class="layout-right">
            <a href="<?= $requestUrl ?>/logout" class="button button-primary">Déconnexion</a>
        </li>
        <li>
            <p class="welcome">Hi, mister <strong><?= $userSession->getFirstName() ?> <?= $userSession->getLastName() ?></strong></p>
        </li>
        <?php else: ?>
        <li class="layout-right">
            <a href="<?= $requestUrl ?>/login" class="button button-primary">Connexion</a>
        </li>
        <?php endif ?>
    </ul>
</nav>

<main>
    <!-- Message de notification -->
    <?php if ($flashBag->hasMessages()): ?>
        <aside class="notice" id="notice">
            <?php foreach ($flashBag->fetchMessages() as $message): ?>
                <p><?= $message ?></p>
            <?php endforeach ?>
        </aside>
    <?php endif ?>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fas fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>


<!-- Librairie jQuery -->
<script src="<?= $wwwUrl ?>/js/jquery-3.4.1.js"></script>

<!-- JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/utilities.js"></script>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>
